//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probavosem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид карты.
    /// </summary>
    // *** Start programmer edit section *** (ВидКарты CustomAttributes)

    // *** End programmer edit section *** (ВидКарты CustomAttributes)
    public enum ВидКарты
    {
        
        // *** Start programmer edit section *** (ВидКарты.Универсальная CustomAttributes)

        // *** End programmer edit section *** (ВидКарты.Универсальная CustomAttributes)
        [Caption("Универсальная")]
        Универсальная,
        
        // *** Start programmer edit section *** (ВидКарты.Гостевая CustomAttributes)

        // *** End programmer edit section *** (ВидКарты.Гостевая CustomAttributes)
        [Caption("Гостевая")]
        Гостевая,
    }
}
