//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probavosem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход гостя.
    /// </summary>
    // *** Start programmer edit section *** (ВходГостя CustomAttributes)

    // *** End programmer edit section *** (ВходГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Вход гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходГостяE", new string[] {
            "РегистрГостей as \'ФИО\'",
            "РегистрГостей.ФИО as \'ФИО\'",
            "РегистрГостей.Карта.КодКарты as \'Карта\'"}, Hidden=new string[] {
            "РегистрГостей.ФИО"})]
    [MasterViewDefineAttribute("ВходГостяE", "РегистрГостей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ВходГостя : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probavosem.РегистрГостей fРегистрГостей;
        
        private IIS.Probavosem.РегистрВхода fРегистрВхода;
        
        // *** Start programmer edit section *** (ВходГостя CustomMembers)

        // *** End programmer edit section *** (ВходГостя CustomMembers)

        
        /// <summary>
        /// Вход гостя.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.РегистрГостей CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.РегистрГостей CustomAttributes)
        [PropertyStorage(new string[] {
                "РегистрГостей"})]
        [NotNull()]
        public virtual IIS.Probavosem.РегистрГостей РегистрГостей
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрГостей Get start)

                // *** End programmer edit section *** (ВходГостя.РегистрГостей Get start)
                IIS.Probavosem.РегистрГостей result = this.fРегистрГостей;
                // *** Start programmer edit section *** (ВходГостя.РегистрГостей Get end)

                // *** End programmer edit section *** (ВходГостя.РегистрГостей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрГостей Set start)

                // *** End programmer edit section *** (ВходГостя.РегистрГостей Set start)
                this.fРегистрГостей = value;
                // *** Start programmer edit section *** (ВходГостя.РегистрГостей Set end)

                // *** End programmer edit section *** (ВходГостя.РегистрГостей Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probavosem.РегистрВхода.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.РегистрВхода CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.РегистрВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РегистрВхода"})]
        public virtual IIS.Probavosem.РегистрВхода РегистрВхода
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Get start)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Get start)
                IIS.Probavosem.РегистрВхода result = this.fРегистрВхода;
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Get end)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Set start)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Set start)
                this.fРегистрВхода = value;
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Set end)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходГостяE", typeof(IIS.Probavosem.ВходГостя));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВходГостя.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)
    public class DetailArrayOfВходГостя : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probavosem.DetailArrayOfВходГостя members)

        // *** End programmer edit section *** (IIS.Probavosem.DetailArrayOfВходГостя members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВходГостя by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВходГостя.
        /// </summary>
        public DetailArrayOfВходГостя(IIS.Probavosem.РегистрВхода fРегистрВхода) : 
                base(typeof(ВходГостя), ((ICSSoft.STORMNET.DataObject)(fРегистрВхода)))
        {
        }
        
        public IIS.Probavosem.ВходГостя this[int index]
        {
            get
            {
                return ((IIS.Probavosem.ВходГостя)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probavosem.ВходГостя dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
