//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probavosem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр входа.
    /// </summary>
    // *** Start programmer edit section *** (РегистрВхода CustomAttributes)

    // *** End programmer edit section *** (РегистрВхода CustomAttributes)
    [AutoAltered()]
    [Caption("Регистрация входа в номер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрВходаE", new string[] {
            "Дата as \'Дата\'",
            "Комната as \'Комната\'",
            "Комната.Номер as \'Номер\'"}, Hidden=new string[] {
            "Комната.Номер"})]
    [AssociatedDetailViewAttribute("РегистрВходаE", "ВходГостя", "ВходГостяE", true, "", "Вход гостя", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("РегистрВходаE", "ВходСотрудника", "ВходСотрудникаE", true, "", "Вход сотрудника", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РегистрВходаE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("РегистрВходаL", new string[] {
            "Дата as \'Дата\'",
            "Комната.Номер as \'Номер\'"})]
    public class РегистрВхода : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Probavosem.Комната fКомната;
        
        private IIS.Probavosem.DetailArrayOfВходГостя fВходГостя;
        
        private IIS.Probavosem.DetailArrayOfВходСотрудника fВходСотрудника;
        
        // *** Start programmer edit section *** (РегистрВхода CustomMembers)

        // *** End programmer edit section *** (РегистрВхода CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегистрВхода.Дата CustomAttributes)

        // *** End programmer edit section *** (РегистрВхода.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегистрВхода.Дата Get start)

                // *** End programmer edit section *** (РегистрВхода.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегистрВхода.Дата Get end)

                // *** End programmer edit section *** (РегистрВхода.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрВхода.Дата Set start)

                // *** End programmer edit section *** (РегистрВхода.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегистрВхода.Дата Set end)

                // *** End programmer edit section *** (РегистрВхода.Дата Set end)
            }
        }
        
        /// <summary>
        /// Регистр входа.
        /// </summary>
        // *** Start programmer edit section *** (РегистрВхода.Комната CustomAttributes)

        // *** End programmer edit section *** (РегистрВхода.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.Probavosem.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (РегистрВхода.Комната Get start)

                // *** End programmer edit section *** (РегистрВхода.Комната Get start)
                IIS.Probavosem.Комната result = this.fКомната;
                // *** Start programmer edit section *** (РегистрВхода.Комната Get end)

                // *** End programmer edit section *** (РегистрВхода.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрВхода.Комната Set start)

                // *** End programmer edit section *** (РегистрВхода.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (РегистрВхода.Комната Set end)

                // *** End programmer edit section *** (РегистрВхода.Комната Set end)
            }
        }
        
        /// <summary>
        /// Регистр входа.
        /// </summary>
        // *** Start programmer edit section *** (РегистрВхода.ВходГостя CustomAttributes)

        // *** End programmer edit section *** (РегистрВхода.ВходГостя CustomAttributes)
        public virtual IIS.Probavosem.DetailArrayOfВходГостя ВходГостя
        {
            get
            {
                // *** Start programmer edit section *** (РегистрВхода.ВходГостя Get start)

                // *** End programmer edit section *** (РегистрВхода.ВходГостя Get start)
                if ((this.fВходГостя == null))
                {
                    this.fВходГостя = new IIS.Probavosem.DetailArrayOfВходГостя(this);
                }
                IIS.Probavosem.DetailArrayOfВходГостя result = this.fВходГостя;
                // *** Start programmer edit section *** (РегистрВхода.ВходГостя Get end)

                // *** End programmer edit section *** (РегистрВхода.ВходГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрВхода.ВходГостя Set start)

                // *** End programmer edit section *** (РегистрВхода.ВходГостя Set start)
                this.fВходГостя = value;
                // *** Start programmer edit section *** (РегистрВхода.ВходГостя Set end)

                // *** End programmer edit section *** (РегистрВхода.ВходГостя Set end)
            }
        }
        
        /// <summary>
        /// Регистр входа.
        /// </summary>
        // *** Start programmer edit section *** (РегистрВхода.ВходСотрудника CustomAttributes)

        // *** End programmer edit section *** (РегистрВхода.ВходСотрудника CustomAttributes)
        public virtual IIS.Probavosem.DetailArrayOfВходСотрудника ВходСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (РегистрВхода.ВходСотрудника Get start)

                // *** End programmer edit section *** (РегистрВхода.ВходСотрудника Get start)
                if ((this.fВходСотрудника == null))
                {
                    this.fВходСотрудника = new IIS.Probavosem.DetailArrayOfВходСотрудника(this);
                }
                IIS.Probavosem.DetailArrayOfВходСотрудника result = this.fВходСотрудника;
                // *** Start programmer edit section *** (РегистрВхода.ВходСотрудника Get end)

                // *** End programmer edit section *** (РегистрВхода.ВходСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрВхода.ВходСотрудника Set start)

                // *** End programmer edit section *** (РегистрВхода.ВходСотрудника Set start)
                this.fВходСотрудника = value;
                // *** Start programmer edit section *** (РегистрВхода.ВходСотрудника Set end)

                // *** End programmer edit section *** (РегистрВхода.ВходСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрВходаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрВходаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрВходаE", typeof(IIS.Probavosem.РегистрВхода));
                }
            }
            
            /// <summary>
            /// "РегистрВходаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрВходаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрВходаL", typeof(IIS.Probavosem.РегистрВхода));
                }
            }
        }
    }
}
